#- name: install iptables-persistent
#  become: true
#  apt:
#    name: iptables-persistent
#    state: present

- name: open ports for haproxy
  become: true
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 8443
    jump: ACCEPT

- name: open ports for ssh
  become: true
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 22
    jump: ACCEPT

- name: allow loopback in
  become: true
  iptables:
    chain: INPUT
    in_interface: lo
    jump: ACCEPT

- name: allow loopback out
  become: true
  iptables:
    chain: OUTPUT
    out_interface: lo
    jump: ACCEPT

- name: allow established and related
  become: true
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: block invalid
  become: true
  iptables:
    chain: INPUT
    ctstate: INVALID
    jump: DROP

- name: drop input by default
  become: true
  iptables:
    chain: INPUT
    policy: DROP

